language: csharp
solution: ResDiffAnalyse.sln
install:
  - nuget # lets get version number
  - nuget restore ResDiffAnalyse.sln -Verbosity detailed
  - nuget update ResDiffAnalyse.sln -Verbosity detailed
