language: csharp
solution: ResDiffAnalyse.sln
install:
  - nuget # lets get version number
  - nuget restore FindReferenceWithRoslyn.sln -Verbosity detailed
  - nuget update FindReferenceWithRoslyn.sln -Verbosity detailed
